In [1]:
import numpy as np

In [2]:
#numpy arrays(dizileri)

In [3]:
benimListem = [20,30,40]

In [4]:
type(benimListem)

list

In [5]:
np.array(benimListem) #bunu bir numpy dizisine çevirebiliyoruz

array([20, 30, 40])

In [6]:
type(np.array(benimListem))

numpy.ndarray

In [7]:
matrixListesi = [[10,20,30], [20,30,40], [30,40,50]]

In [8]:
type(matrixListesi)

list

In [9]:
matrixListesi[1][0]

20

In [10]:
np.array(matrixListesi) #matrix görünümü

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [11]:
#Numpy Methodlar

In [12]:
#(arange)

In [13]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
np.arange(0,10) #numpy dizi oluşturuyor

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2) #step = 2

array([0, 2, 4, 6, 8])

In [16]:
#(zeros) #bu bildiğimiz sıfırı oluşturuyor

In [17]:
np.zeros(5) #içinde 5 tane sıfır olan dizi oluşturuyor

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,2)) #matrix içerisinde gösteriyor. neden iki parantez dizi içinde dizi var çünkü

array([[0., 0.],
       [0., 0.]])

In [19]:
#(ones)

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((9,9)) 

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [22]:
#(linspace)

In [23]:
np.linspace(0,10,6)
#belirttiğimiz numaralar arasından boyutlanmış eşit olarak aralık bırakılmış bir dizi oluşturuyor.

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [24]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [25]:
#(eye)

In [26]:
np.eye(3) #burada diagonal yapı 1 gerisi 0 olan matrix dizisi

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
#random

In [28]:
np.random.randn(4)
#rastgele bazı değerler çıkarıyor ve bunu çıkartırken burada kullandığı method:
#standad normal distribustion dediğimiz normal dağılıma uygun veriler çıkarmaya çalısıyor
#radn bize bir numpy dizesi döndürüyor

array([ 0.26093287, -1.60999598,  0.10004092, -0.13242539])

In [29]:
np.random.randn(4,4) #matrix oluşturuyor rastgele rakamlarla

array([[ 1.54570798e-01,  1.27520233e+00, -2.41205096e-02,
        -3.15937659e-01],
       [-5.42603121e-01,  6.90059072e-01,  4.68319073e-01,
         1.67407010e+00],
       [ 7.67160067e-01,  2.13390069e+00, -4.92197297e-01,
        -1.25864085e+00],
       [-1.89334883e-03,  1.15839775e+00, -2.55410270e-01,
         2.61264352e-01]])

In [30]:
#tek bir değer döndürmek isteseydik o zaman "randint" kullanacaktık örneğin;

In [31]:
np.random.randint(1,10) #her seferinde(çalışmasında) başka bir değer döndürecek

8

In [32]:
np.random.randint(1,10,5) #buradaki 5 ile kaç tane rakam isteğimizi söylüyoruz
#1 dahil 10 dahil değil 5 tane rakam döndürüyor
#yine her çalışmasında farklı rakam döndürecek

array([1, 2, 1, 4, 5])

In [33]:
np.random.randint(1,300,5)

array([280,  52, 197,  69, 215])

In [34]:
benimNumpy = np.arange(30)
benimNumpy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
benimRandom = np.random.randint(0,40,7)
benimRandom

array([16, 31, 15, 32, 30, 14, 13])

In [36]:
#Numpy Dizi Methodları

In [38]:
benimNumpy.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [39]:
benimNumpy.max()

29

In [40]:
benimRandom.max()

32

In [41]:
benimRandom.min()

13

In [42]:
benimRandom.argmax() #kaçıncı indekte olduğunu alabiliyoruz

3

In [43]:
benimRandom.argmin() #en küçük değer

6

In [46]:
benimNumpy.shape

(30,)

In [47]:
benimRandom.shape

(7,)

In [48]:
reshapeDizim = benimNumpy.reshape(5,6)
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [49]:
reshapeDizim.shape

(5, 6)