In [1]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5] #listelerle birebir aynı şeye sahip

5

In [5]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [6]:
benimDizim[3:8] = -5 #3 ve 8 arasında 7.index değeri -5 oldu
#bu ayrı bir dize oluşturmadı elemanları değiştirdi

In [7]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [8]:
baskaDizi = np.arange(0,24)

In [9]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [10]:
slicingDizi = baskaDizi[4:9]

In [11]:
slicingDizi

array([4, 5, 6, 7, 8])

In [12]:
type(slicingDizi)

numpy.ndarray

In [13]:
slicingDizi[:]

array([4, 5, 6, 7, 8])

In [14]:
slicingDizi[:] = 700 #içindeki tüm rakamları 700 e eşitleme

In [15]:
slicingDizi

array([700, 700, 700, 700, 700])

In [16]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [22]:
ornekDizi = np.arange(0,24)
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
ornekDiziKopyasi = ornekDizi.copy()

In [24]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
ornekDiziKopyasiSlicing = ornekDiziCopy[3:6]
ornekDiziKopyasiSlicing

array([3, 4, 5])

In [26]:
ornekDiziKopyasiSlicing[:] = 800

In [27]:
ornekDiziKopyasiSlicing

array([800, 800, 800])

In [28]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [29]:
ornekDizi 
#bir dizenin içinden belli rakam alıp işyeceksek ve orjinal verisetinde bir değişiklik olmasını istemiyorsak copy() al

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [30]:
#Matrix Indexler

In [37]:
benimListem = [[10,20,30], [20,30,40],[30,40,50]]

In [38]:
benimListem

[[10, 20, 30], [20, 30, 40], [30, 40, 50]]

In [39]:
benimMatrixDizi= np.array(benimListem)

In [40]:
benimMatrixDizi

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [41]:
benimMatrixDizi[0]

array([10, 20, 30])

In [42]:
benimMatrixDizi[1][2]

40

In [43]:
benimMatrixDizi[1, 2]

40

In [44]:
benimMatrixDizi[1:, 2]

array([40, 50])

In [45]:
benimMatrixDizi[2:,2]

array([50])

In [46]:
benimMatrixDizi[1:,1]

array([30, 40])

In [47]:
benimMatrixDizi[0:,2]

array([30, 40, 50])

In [48]:
benimMatrixDizi[2:,1:]

array([[40, 50]])

In [49]:
benimMatrixDizi[2:,0:]

array([[30, 40, 50]])

In [51]:
benimMatrixDizi[:2,2:]

array([[30],
       [40]])

In [52]:
benimMatrixDizi[2:, 2:]

array([[50]])

In [55]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9], [10,11,12,13,14], [15,16,17,18,19], [20,21,22,23,24]]

In [56]:
yeniListe

[[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24]]

In [57]:
yeniMatrix = np.array(yeniListe)
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
yeniMatrix[2]

array([10, 11, 12, 13, 14])

In [59]:
yeniMatrix[[0,2,4]] #fancy index

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])