In [4]:
import numpy as np
yeniDizi = np.random.randint(1,100,20)
yeniDizi

array([40, 33, 30,  9, 87,  7, 47, 20, 73, 14, 86, 86,  9, 49, 61, 40, 36,
       43, 94, 97])

In [5]:
yeniDizi > 24 #24 den büyük elemanları boolen olarak döndürüyor

array([ True,  True,  True, False,  True, False,  True, False,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True])

In [6]:
yeniDizi

array([40, 33, 30,  9, 87,  7, 47, 20, 73, 14, 86, 86,  9, 49, 61, 40, 36,
       43, 94, 97])

In [7]:
sonuc = yeniDizi > 24
sonuc

array([ True,  True,  True, False,  True, False,  True, False,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True])

In [8]:
yeniDizi[sonuc] #sadece 24den büyük rakamları getiriyor

array([40, 33, 30, 87, 47, 73, 86, 86, 49, 61, 40, 36, 43, 94, 97])

In [9]:
yeniDizi[yeniDizi > 24] #yine aynı sonucu verecekti bir değere atamadan baksaydım

array([40, 33, 30, 87, 47, 73, 86, 86, 49, 61, 40, 36, 43, 94, 97])

In [10]:
sonDizi = np.arange(0,24)

In [11]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
sonDizi + sonDizi #bütün elemanları kendisi ile topluyor

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [13]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [14]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [15]:
sonDizi / sonDizi
#burada geçerli olmayan bir değerle karşılaştığımız için bizi uyarıyor nan yazıyor
#ama işleme de devam ediyor

<ipython-input-15-20a5ae775714>:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [16]:
np.sqrt(sonDizi) #karekökünü aldık

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [17]:
np.max(sonDizi)

23

In [18]:
np.min(sonDizi)

0

In [20]:
sonDizi.max()

23